version: '3.8'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/
      - spring.security.user.name=admin
      - spring.security.user.password=secret
    volumes:
      - ./src/main/resources:/config
    networks:
      - auth_net

networks:
  auth_net:
    external: true
